### ISSUE TITLE
Bastion fails to be created when `networks.vpc.id` is specified

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-alicloud#500]
**How to categorize this issue?**

/area ops-productivity
/kind bug
/platform alicloud

**What happened**:
Cannot ssh to a Node coming from a Shoot that specifies `networks.vpc.id` (pre-existing VPC).

**What you expected to happen**:
To be able to ssh to a Node coming from a Shoot that specifies `networks.vpc.id` (pre-existing VPC).

**How to reproduce it (as minimally and precisely as possible)**:
1. Try to ssh to a Node coming from a Shoot that specifies `networks.vpc.id` (pre-existing VPC).

2. Make sure that the Bastion creation fails with:

```yaml
status:
  lastError:
    description: 'Error reconciling bastion: shoot vpc must be not empty'
    lastUpdateTime: "2022-06-15T09:10:24Z"
  lastOperation:
    description: 'Error reconciling bastion: shoot vpc must be not empty'
    lastUpdateTime: "2022-06-15T09:10:24Z"
    progress: 50
    state: Error
    type: Create
  observedGeneration: 1
```

AFAIS, currently the logic always relies the VPC name to be `%s-vpc` which is not true for end-user specified VPCs.
https://github.com/gardener/gardener-extension-provider-alicloud/blob/1d2976f8ca1238888517cfd9be62b66fa803f94b/pkg/controller/bastion/options.go#L112-L115

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.37.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
