### ISSUE TITLE
Remove zone field in shoot controlPlaneConfig section

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener-extension-provider-alicloud#63]
**What would you like to be added**:
Here is the example config in Shoot for Alicloud:
```
  provider:
    type: alicloud
    controlPlaneConfig:
      apiVersion: alicloud.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      zone: cn-shanghai-f
```
This zone is used for cloud controller manager config. Zone info is used in a configmap (`cloud-provider-config`) in shoot controlplain namespace.
1. Use anyzone defined in worker groups. The first one is OK.
2. Change configmap to secret.
**Why is this needed**:
